---

- hosts: auth
  vars_files:
    - vars/users.yml
    - vars/software.yml
    - vars/secrets.yml
    - vars/auth.yml

  roles:
  - ansible-base
  - ansible-sshd
  - ansible-node-exporter
  - ansible-ldap
