---

- hosts: auth
  vars_files:
    - vars/users.yml
    - vars/software_redhat.yml
    - vars/secrets.yml
    - vars/ldap.yml

  roles:
  - ansible-base
  - ansible-sshd
  - ansible-node-exporter
  - ansible-389ds
