---

- hosts: devops
  vars_files:
    - vars/users.yml
    - vars/software.yml

  roles:
  - ansible-base
  - ansible-sshd
  - ansible-node-exporter

  tasks:
  - name: enable firewall
    import_tasks: tasks/enablefirewall.yml
    become: true

# Tickets
- name: Call tickets playbook
  import_playbook: ./tickets.yml

# Monitoring
- name: Call monitoring playbook
  import_playbook: ./monitoring.yml

