---

- hosts: custom02
  vars_files:
    - vars/users.yml
    - vars/software.yml
    - vars/secrets.yml

  tasks:
  - name: Setup Monitoring
    import_tasks: ./roles/ansible-docker/tasks/monitoring.yml

  roles:
    - ansible-base
    - ansible-sshd
    - ansible-node-exporter
    - ansible-docker
    - ansible-letsencrypt
    - ansible-jitsi

  vars:
    jitsi_manual_docker_build: false
