---

- hosts: prometheus
  vars_files:
    - vars/secrets.yml
    - vars/grafana.yml

  tasks:
  - name: Enable 443
    ufw:
      rule: allow
      port: https

  - name: Enable 80
    ufw:
      rule: allow
      port: http

  - name: Enable blackbox_exporter Port
    ufw:
      rule: allow
      port: '9115'

  roles:
  - ansible-grafana
  - ansible-letsencrypt
  - ansible-nginx

