---

- hosts: jitsi_rocks
  tasks:
  - name: Disable Firewall
    ufw:
      state: disabled
      default: allow

  - name: Enable docker exporter
    import_tasks: tasks/docker_exporter.yml

  roles:
  - ansible-node-exporter

