---

# Letsencrypt prometheus
- hosts: prometheus
  vars_files:
    - vars/prometheus_letsencrypt.yml
  roles:
  - ansible-letsencrypt

# Letsencrypt monitor
- hosts: monitor
  vars_files:
    - vars/grafana_letsencrypt.yml
  roles:
  - ansible-letsencrypt

# Main
- hosts: monitor
  vars_files:
    - vars/prometheus.yml
    - vars/secrets.yml

  tasks:
  - name: Enable blackbox_exporter Port
    ufw:
      rule: allow
      port: '9115'

  roles:
  - ansible-base
  - ansible-sshd
  - ansible-prometheus
  - ansible-blackbox-exporter
  - ansible-grafana
  - ansible-nginx

