---
- hosts: monitor:prometheus
  tasks:
  - name: Enable 443
    ufw:
      rule: allow
      port: https

  - name: Enable 80
    ufw:
      rule: allow
      port: http

  - name: Enable blackbox_exporter Port
    ufw:
      rule: allow
      port: '9115'

- hosts: prometheus
  vars_files:
    - vars/prometheus.yml
    - vars/prometheus_letsencrypt.yml
    - vars/secrets.yml

  roles:
  - ansible-letsencrypt

- hosts: monitor
  vars_files:
    - vars/prometheus.yml
    - vars/grafana_letsencrypt.yml
    - vars/secrets.yml

  roles:
  - ansible-letsencrypt

- hosts: monitor
  vars_files:
    - vars/prometheus.yml
    - vars/secrets.yml

  roles:
  - ansible-prometheus
  - ansible-blackbox-exporter
  - ansible-grafana
  - ansible-nginx

