---

- hosts: prometheus
  tasks:
    - name: Enable 443
      ufw:
        rule: allow
        port: https
    - name: Enable 80
      ufw:
        rule: allow
        port: http

  roles:
  - ansible-prometheus
  - ansible-grafana
  - ansible-letsencrypt
  - ansible-nginx

  vars:
    letsencrypt_webroot_path: /var/www
    letsencrypt_email: letsencrypt@open-infrastructure.de
    letsencrypt_renewal_command_args: '--renew-hook "systemctl restart nginx"'
    letsencrypt_cert_domains:
    - "{{ ansible_host }}"
    nginx_vhosts:
      - listen: "80"
        server_name: "{{ ansible_host }} www.{{ ansible_host }}"
        filename: "{{ ansible_host }}.80.conf"
        return: "301 https://$host$request_uri"
        state: "present"

      - listen: "443 ssl http2"
        server_name: "{{ ansible_host }}"
        state: "present"
        enable_ssl: true
        extra_parameters: |
          location / {
            proxy_pass http://prometheus.open-infrastructure.de:3000;
          }
          proxy_redirect http://prometheus.open-infrastructure.de:3000 https://prometheus.open-infrastructure.de;

    nginx_ssl_trusted_certificate: "/etc/letsencrypt/live/{{ ansible_host }}/chain.pem"
    nginx_ssl_certificate: "/etc/letsencrypt/live/{{ ansible_host }}/fullchain.pem"
    nginx_ssl_certificate_key: "/etc/letsencrypt/live/{{ ansible_host }}/privkey.pem"
    nginx_tls_acme_challenge_root_location: "/var/lib/letsencrypt/"

    prometheus_web_external_url: "http://prometheus.open-infrastructure.de"
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        - fsn1-gw1.vpn.open-infrastructure.de:9100
        - de-bra-1.jitsi.rocks:9100
        - de-wob-1.jitsi.rocks:9100
        - de-fsn-1.jitsi.rocks:9100
        - de-fsn-2.jitsi.rocks:9100
        - de-fsn-3.jitsi.rocks:9100
        - de-nue-1.jitsi.rocks:9100
        - de-nue-2.jitsi.rocks:9100
        - fi-hel-2.jitsi.rocks:9100
        - fi-hel-2.jitsi.rocks:9100
        - nl-ams-1.jitsi.rocks:9100
        - us-nyc-1.jitsi.rocks:9100
        - gb-lon-1.jitsi.rocks:9100
        - bbb.jitsi.rocks:9100
        - bbb1.jitsi.rocks:9100
        - tickets.open-infrastructure.de:9100
    grafana_address: "prometheus.open-infrastructure.de"
    grafana_port: 3000
    grafana_auth:
      anonymous:
        org_name: "Open Data"
        org_role: Viewer
      basic:
        enabled: true
    grafana_security:
      admin_user: admin
      admin_password: grafanaSecureAdminPassword1234
