---

- hosts: vpn
  vars_files:
    - vars/users.yml
    - vars/software.yml

  roles:
  - ansible-base
  - ansible-sshd
  - ansible-node-exporter

  tasks:
  - name: enable firewall
    import_tasks: tasks/enablefirewall.yml
    become: true

- hosts: ipsec_gateways
  roles:
    - ansible-strongswan

