all:
  children:
    devops:
      hosts:
        zammad:
          ansible_host: tickets.open-infrastructure.de
          ansible_user: root

        auth:
          ansible_host: auth.open-infrastructure.de
          ansible_user: root

      children:
        monitoring:
          hosts:
            prometheus:
              ansible_host: prometheus.open-infrastructure.de
              ansible_user: root

            monitor:
              ansible_host: monitor.open-infrastructure.de
              ansible_user: root
          children:
            elk:
              hosts:
                kibana:
                  ansible_host: kibana.open-infrastructure.de
                  ansible_user: root


