nginx_vhosts:
  - listen: "80"
    server_name: "monitor.open-infrastructure.de www.monitor.open-infrastructure.de"
    filename: "prometheus.80.conf"
    return: "301 https://prometheus.open-infrastructure.de/$request_uri"
    state: "present"

  - listen: "80"
    server_name: "prometheus.open-infrastructure.de www.prometheus.open-infrastructure.de"
    filename: "monitor.80.conf"
    return: "301 https://prometheus.open-infrastructure.de/$request_uri"
    state: "present"

  - listen: "443 ssl http2"
    server_name: "prometheus.open-infrastructure.de"
    state: "present"
    extra_parameters: |
      location / {
        proxy_pass http://prometheus.open-infrastructure.de:9090;
      }
      ssl_trusted_certificate "/etc/letsencrypt/live/prometheus.open-infrastructure.de/chain.pem";
      ssl_certificate "/etc/letsencrypt/live/prometheus.open-infrastructure.de/fullchain.pem";
      ssl_certificate_key "/etc/letsencrypt/live/prometheus.open-infrastructure.de/privkey.pem";
      location ^~ /.well-known/acme-challenge/ {
        allow all;
        root "/var/lib/letsencrypt/";
        default_type "text/plain";
        try_files $uri =404;
      }
      {{ nginx_tls_parameters }}


  - listen: "443 ssl http2"
    server_name: "monitor.open-infrastructure.de"
    state: "present"
    extra_parameters: |
      location / {
        proxy_pass http://monitor.open-infrastructure.de:3000;
      }
      ssl_trusted_certificate "/etc/letsencrypt/live/monitor.open-infrastructure.de/chain.pem";
      ssl_certificate "/etc/letsencrypt/live/monitor.open-infrastructure.de/fullchain.pem";
      ssl_certificate_key "/etc/letsencrypt/live/monitor.open-infrastructure.de/privkey.pem";
      location ^~ /.well-known/acme-challenge/ {
        allow all;
        root "/var/lib/letsencrypt/";
        default_type "text/plain";
        try_files $uri =404;
      }
      {{ nginx_tls_parameters }}

grafana_address: "monitor.open-infrastructure.de"
grafana_port: 3000
grafana_auth:
  anonymous:
    org_name: "Open Data"
    org_role: Viewer
  basic:
    enabled: true

blackbox_exporter_configuration_modules:
  icmp_test:
    prober: icmp
    timeout: 10s
    icmp:
      preferred_ip_protocol: ip6
  dns_test:
    prober: dns
    timeout: 10s
    dns:
      preferred_ip_protocol: ip6
      validate_answer_rrs:
        fail_if_matches_regexp: [test]

prometheus_web_external_url: "http://prometheus.open-infrastructure.de"

prometheus_scrape_configs:
  - job_name: docker_exporter
    metrics_path: "/metrics"
    file_sd_configs:
    - files:
      - "{{ prometheus_config_dir }}/file_sd/docker_exporter.yml"

  - job_name: gitlab
    metrics_path: "/-/metrics"
    params:
      token: [tc_RERu_L51BHf6yQ-Tt]
    file_sd_configs:
    - files:
      - "{{ prometheus_config_dir }}/file_sd/gitlab.yml"

  - job_name: node_exporter
    metrics_path: "/metrics"
    file_sd_configs:
    - files:
      - "{{ prometheus_config_dir }}/file_sd/node_exporter.yml"

  - job_name: blackbox_exporter
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.

    file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/blackbox_exporter.yml

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.

prometheus_targets:
  gitlab:
  - targets:
    - git.open-infrastructure.de

  docker_exporter:
  - targets:
    - de-bra-1.jitsi.rocks:9417
    - de-wob-2.jitsi.rocks:9417
    - de-fsn-1.jitsi.rocks:9417
    - fi-hel-1.jitsi.rocks:9417
    - fi-hel-2.jitsi.rocks:9417
    - nl-ams-1.jitsi.rocks:9417
    - us-nyc-1.jitsi.rocks:9417
    - gb-lon-1.jitsi.rocks:9417

  blackbox_exporter:
  - targets:
    - https://de-bra-1.jitsi.rocks
    - https://de-wob-2.jitsi.rocks
    - https://de-fsn-1.jitsi.rocks
    - https://fi-hel-1.jitsi.rocks
    - https://fi-hel-2.jitsi.rocks
    - https://nl-ams-1.jitsi.rocks
    - https://us-nyc-1.jitsi.rocks
    - https://gb-lon-1.jitsi.rocks
    - https://bbb.jitsi.rocks
    - https://tickets.open-infrastructure.de
    - https://git.open-infrastructure.de

  node_exporter:
  - targets:
    - localhost:9100
    - de-fsn1-gw1.vpn.open-infrastructure.de:9100
    - de-bra-1.jitsi.rocks:9100
    - de-wob-2.jitsi.rocks:9100
    - de-fsn-1.jitsi.rocks:9100
    - fi-hel-1.jitsi.rocks:9100
    - fi-hel-2.jitsi.rocks:9100
    - nl-ams-1.jitsi.rocks:9100
    - us-nyc-1.jitsi.rocks:9100
    - gb-lon-1.jitsi.rocks:9100
    - bbb.jitsi.rocks:9100
    - tickets.open-infrastructure.de:9100
    - monitor.open-infrastructure.de:9100
    - auth.open-infrastructure.de:9100
